/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Source */
        post: operations["import_source_api_projects__slug__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Code */
        post: operations["create_code_api_projects__slug__codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codes/{code_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Code */
        put: operations["update_code_api_projects__slug__codes__code_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codebook/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze */
        post: operations["freeze_api_projects__slug__codebook_freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/coding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coding */
        post: operations["coding_api_projects__slug__coding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Memo */
        post: operations["create_memo_api_projects__slug__memos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/memos/{memo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Memo */
        put: operations["update_memo_api_projects__slug__memos__memo_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case */
        post: operations["create_case_api_projects__slug__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Case */
        put: operations["update_case_api_projects__slug__cases__case_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieval */
        get: operations["retrieval_api_projects__slug__retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_projects__slug__matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_projects__slug__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/ai/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Availability */
        get: operations["availability_api_projects__slug__ai_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify */
        post: operations["classify_api_projects__slug__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_projects__slug__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_projects__slug__experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_projects__slug__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Availability */
        Availability: {
            /** Allow External */
            allow_external: boolean;
            /** Backends */
            backends: components["schemas"]["BackendAvailability"][];
        };
        /** BackendAvailability */
        BackendAvailability: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** External */
            external: boolean;
            /** Reason */
            reason: string;
        };
        /** CaseInput */
        CaseInput: {
            /** Name */
            name: string;
            /** Source Ids */
            source_ids?: number[];
            /** Attributes */
            attributes?: {
                [key: string]: string;
            };
        };
        /** ClassifyInput */
        ClassifyInput: {
            /** Backend */
            backend?: string | null;
            /** Model */
            model?: string | null;
            /** Segment Ids */
            segment_ids?: number[] | null;
            /**
             * Task
             * @default classification
             * @enum {string}
             */
            task: "classification" | "escalation";
        };
        /** ClassifyResult */
        ClassifyResult: {
            /** Run Id */
            run_id: string;
            /** Backend */
            backend: string;
            /** Model */
            model: string;
            /** Segments */
            segments: number;
            /** Calls */
            calls: number;
            /** Cache Hits */
            cache_hits: number;
            /** Escalated Segments */
            escalated_segments: number;
            /** Suggestion Ids */
            suggestion_ids: number[];
            /** Predictions */
            predictions: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
            /** Errors */
            errors: string[];
        };
        /** CodeInput */
        CodeInput: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Definition
             * @default
             */
            definition: string;
            /**
             * Include
             * @default
             */
            include: string;
            /**
             * Exclude
             * @default
             */
            exclude: string;
            /** Examples Pos */
            examples_pos?: string[];
            /** Examples Neg */
            examples_neg?: string[];
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "archived";
        };
        /** CodingInput */
        CodingInput: {
            /** Segment Id */
            segment_id: number;
            /** Code Id */
            code_id: number;
            /**
             * Span Start
             * @default 0
             */
            span_start: number;
            /** Span End */
            span_end?: number | null;
            /** Codebook Version Id */
            codebook_version_id?: number | null;
            /**
             * Action
             * @default assign
             * @enum {string}
             */
            action: "assign" | "remove";
            /**
             * Actor
             * @default researcher
             */
            actor: string;
        };
        /** EvaluateInput */
        EvaluateInput: {
            /** Backend */
            backend?: string | null;
            /** Model */
            model?: string | null;
        };
        /** EvaluationResult */
        EvaluationResult: {
            /** Id */
            id: number;
            /** Split */
            split: string;
            /** Backend */
            backend: string;
            /** Model */
            model: string;
            /** Codebook Version Id */
            codebook_version_id: number;
            /** Pipeline Version */
            pipeline_version: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Agent */
            agent: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "KEEP" | "REVERT";
            /** Reason */
            reason: string;
            /** Hypothesis */
            hypothesis: string;
            /** Before Json */
            before_json: string;
            /** After Json */
            after_json: string;
            /** Changed Files Json */
            changed_files_json: string;
            /** Commit Hash */
            commit_hash: string | null;
            /** Tag */
            tag: string | null;
            /** Created At */
            created_at: string;
        };
        /** ExportResult */
        ExportResult: {
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Content */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** IdResult */
        IdResult: {
            /** Id */
            id: number;
        };
        /** ImportInput */
        ImportInput: {
            /** Name */
            name: string;
            /** Content */
            content: string;
            /**
             * Format
             * @enum {string}
             */
            format: "txt" | "md" | "csv";
            /**
             * Text Column
             * @default text
             */
            text_column: string;
            /**
             * Case Column
             * @default case
             */
            case_column: string;
            /**
             * Speaker Column
             * @default speaker
             */
            speaker_column: string;
            /** Attribute Columns */
            attribute_columns?: string[];
            /** Version Of */
            version_of?: number | null;
        };
        /** ImportResult */
        ImportResult: {
            /** New Sources */
            new_sources: number;
            /** Source Ids */
            source_ids: number[];
            /** New Segments */
            new_segments: number;
        };
        /** MemoInput */
        MemoInput: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Segment Id */
            segment_id?: number | null;
            /** Code Id */
            code_id?: number | null;
        };
        /** ProjectInput */
        ProjectInput: {
            /** Name */
            name: string;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** ReviewInput */
        ReviewInput: {
            /** Suggestion Id */
            suggestion_id: number;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject";
            /**
             * Actor
             * @default researcher
             */
            actor: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workspace */
        Workspace: {
            project: components["schemas"]["ProjectSummary"];
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Segments */
            segments: {
                [key: string]: unknown;
            }[];
            /** Cases */
            cases: {
                [key: string]: unknown;
            }[];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            }[];
            /** Source Cases */
            source_cases: {
                [key: string]: unknown;
            }[];
            /** Codes */
            codes: {
                [key: string]: unknown;
            }[];
            /** Codebook Versions */
            codebook_versions: {
                [key: string]: unknown;
            }[];
            /** Coding Events */
            coding_events: {
                [key: string]: unknown;
            }[];
            /** Current Codings */
            current_codings: {
                [key: string]: unknown;
            }[];
            /** Suggestions */
            suggestions: {
                [key: string]: unknown;
            }[];
            /** Memos */
            memos: {
                [key: string]: unknown;
            }[];
            /** Experiments */
            experiments: {
                [key: string]: unknown;
            }[];
            /** Evaluation Runs */
            evaluation_runs: {
                [key: string]: unknown;
            }[];
            /** Routing */
            routing: {
                [key: string]: unknown;
            };
            /** Pipeline Version */
            pipeline_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_projects__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_source_api_projects__slug__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_code_api_projects__slug__codes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_code_api_projects__slug__codes__code_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                code_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_api_projects__slug__codebook_freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coding_api_projects__slug__coding_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memo_api_projects__slug__memos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memo_api_projects__slug__memos__memo_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                memo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_projects__slug__cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_projects__slug__cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieval_api_projects__slug__retrieval_get: {
        parameters: {
            query?: {
                code_id?: number | null;
                case_id?: number | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_api_projects__slug__matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_projects__slug__export_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                no_text?: boolean;
                bundle?: "reproducibility" | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    availability_api_projects__slug__ai_availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_api_projects__slug__classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_projects__slug__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_projects__slug__experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_projects__slug__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
