/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Source */
        post: operations["import_source_api_projects__slug__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Code */
        post: operations["create_code_api_projects__slug__codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codes/{code_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Code */
        put: operations["update_code_api_projects__slug__codes__code_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/codebook/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze */
        post: operations["freeze_api_projects__slug__codebook_freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/coding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coding */
        post: operations["coding_api_projects__slug__coding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/memos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Memo */
        post: operations["create_memo_api_projects__slug__memos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/memos/{memo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Memo */
        put: operations["update_memo_api_projects__slug__memos__memo_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case */
        post: operations["create_case_api_projects__slug__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Case */
        put: operations["update_case_api_projects__slug__cases__case_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieval */
        get: operations["retrieval_api_projects__slug__retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrix */
        get: operations["matrix_api_projects__slug__matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_projects__slug__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/ai/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Availability */
        get: operations["availability_api_projects__slug__ai_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classify */
        post: operations["classify_api_projects__slug__classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_projects__slug__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_projects__slug__experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_projects__slug__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis */
        post: operations["analysis_api_projects__slug__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/analysis/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_projects__slug__analysis_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisCase */
        AnalysisCase: {
            /** Case Id */
            case_id: number;
            /** Name */
            name: string;
            /** Attributes */
            attributes: {
                [key: string]: string | null;
            };
            /** Attribute Status */
            attribute_status: {
                [key: string]: "value" | "missing" | "conflicting";
            };
            /** Code Counts */
            code_counts: {
                [key: string]: number;
            };
        };
        /** AnalysisCorrelation */
        AnalysisCorrelation: {
            /** X Field */
            x_field: string;
            /** Y Field */
            y_field: string;
            /** N */
            n: number;
            /** Pearson R */
            pearson_r: number | null;
            /** Points */
            points: components["schemas"]["AnalysisPoint"][];
        };
        /** AnalysisExcerpt */
        AnalysisExcerpt: {
            /** Segment Id */
            segment_id: number;
            /** Source Id */
            source_id: number;
            /** Source Name */
            source_name: string;
            /** Speaker */
            speaker: string | null;
            /** Text */
            text: string;
            /** Coding Event Ids */
            coding_event_ids: number[];
        };
        /** AnalysisExportRequest */
        AnalysisExportRequest: {
            options?: components["schemas"]["AnalysisOptions"];
            /**
             * Format
             * @default json
             * @enum {string}
             */
            format: "json" | "csv" | "python" | "r";
        };
        /** AnalysisFrequency */
        AnalysisFrequency: {
            /** Code Id */
            code_id: number;
            /** Name */
            name: string;
            /** Segment Count */
            segment_count: number;
            /** Case Count */
            case_count: number;
            /** Segment Percent */
            segment_percent: number;
            /** Case Percent */
            case_percent: number;
            /** Segment Ids */
            segment_ids: number[];
            /** Case Ids */
            case_ids: number[];
            /** Codebook Version Ids */
            codebook_version_ids: number[];
        };
        /** AnalysisGroup */
        AnalysisGroup: {
            /** Value */
            value: string;
            /**
             * Status
             * @enum {string}
             */
            status: "value" | "missing" | "conflicting";
            /** Case Ids */
            case_ids: number[];
            /** Segment Ids */
            segment_ids: number[];
            /** Frequencies */
            frequencies: components["schemas"]["AnalysisFrequency"][];
        };
        /** AnalysisNumeric */
        AnalysisNumeric: {
            /** Field */
            field: string;
            /** Valid */
            valid: number;
            /** Missing */
            missing: number;
            /** Invalid */
            invalid: number;
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** Sample Sd */
            sample_sd: number | null;
            /** Minimum */
            minimum: number | null;
            /** Maximum */
            maximum: number | null;
            /** Values */
            values: components["schemas"]["AnalysisValue"][];
        };
        /** AnalysisOptions */
        AnalysisOptions: {
            /** Source Id */
            source_id?: number | null;
            /** Case Id */
            case_id?: number | null;
            /** Code Ids */
            code_ids?: number[];
            /**
             * Code Match
             * @default any
             * @enum {string}
             */
            code_match: "any" | "all";
            /**
             * Query
             * @default
             */
            query: string;
            /** Group By */
            group_by?: string | null;
            /**
             * Cooccurrence
             * @default segment
             * @enum {string}
             */
            cooccurrence: "segment" | "overlap";
            /** Numeric Fields */
            numeric_fields?: string[];
            /**
             * Min Word Length
             * @default 3
             */
            min_word_length: number;
            /** Stopwords */
            stopwords?: string[];
            /**
             * Top Words
             * @default 30
             */
            top_words: number;
            /**
             * Excerpt Limit
             * @default 100
             */
            excerpt_limit: number;
        };
        /** AnalysisPair */
        AnalysisPair: {
            /** Left Code Id */
            left_code_id: number;
            /** Right Code Id */
            right_code_id: number;
            /** Count */
            count: number;
            /** Union Count */
            union_count: number;
            /** Jaccard */
            jaccard: number | null;
            /** Segment Ids */
            segment_ids: number[];
        };
        /** AnalysisPoint */
        AnalysisPoint: {
            /** Case Id */
            case_id: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** AnalysisReport */
        AnalysisReport: {
            /**
             * Format Version
             * @default 1
             * @constant
             */
            format_version: 1;
            options: components["schemas"]["AnalysisOptions"];
            /** Methods */
            methods: string[];
            /** Warnings */
            warnings: string[];
            /** Source Count */
            source_count: number;
            /** Segment Count */
            segment_count: number;
            /** Case Count */
            case_count: number;
            /** Coded Segment Count */
            coded_segment_count: number;
            /** Selected Segment Ids */
            selected_segment_ids: number[];
            /** Input Hash */
            input_hash: string;
            /** Coding Event Ids */
            coding_event_ids: number[];
            /** Codebook Version Ids */
            codebook_version_ids: number[];
            /** Codebook Hashes */
            codebook_hashes: {
                [key: string]: string;
            };
            /** Pipeline Version */
            pipeline_version: string;
            /** Frequencies */
            frequencies: components["schemas"]["AnalysisFrequency"][];
            /** Groups */
            groups: components["schemas"]["AnalysisGroup"][];
            /** Pairs */
            pairs: components["schemas"]["AnalysisPair"][];
            /** Words */
            words: components["schemas"]["AnalysisWord"][];
            /** Numeric */
            numeric: components["schemas"]["AnalysisNumeric"][];
            /** Correlations */
            correlations: components["schemas"]["AnalysisCorrelation"][];
            /** Excerpts */
            excerpts: components["schemas"]["AnalysisExcerpt"][];
            /** Excerpt Total */
            excerpt_total: number;
            /** Case Rows */
            case_rows: components["schemas"]["AnalysisCase"][];
        };
        /** AnalysisValue */
        AnalysisValue: {
            /** Case Id */
            case_id: number;
            /** Value */
            value: number;
        };
        /** AnalysisWord */
        AnalysisWord: {
            /** Word */
            word: string;
            /** Count */
            count: number;
            /** Segment Count */
            segment_count: number;
            /** Segment Ids */
            segment_ids: number[];
        };
        /** Availability */
        Availability: {
            /** Allow External */
            allow_external: boolean;
            /** Backends */
            backends: components["schemas"]["BackendAvailability"][];
        };
        /** BackendAvailability */
        BackendAvailability: {
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** External */
            external: boolean;
            /** Reason */
            reason: string;
        };
        /** CaseInput */
        CaseInput: {
            /** Name */
            name: string;
            /** Source Ids */
            source_ids?: number[];
            /** Attributes */
            attributes?: {
                [key: string]: string;
            };
        };
        /** ClassifyInput */
        ClassifyInput: {
            /** Backend */
            backend?: string | null;
            /** Model */
            model?: string | null;
            /** Segment Ids */
            segment_ids?: number[] | null;
            /**
             * Task
             * @default classification
             * @enum {string}
             */
            task: "classification" | "escalation";
        };
        /** ClassifyResult */
        ClassifyResult: {
            /** Run Id */
            run_id: string;
            /** Backend */
            backend: string;
            /** Model */
            model: string;
            /** Segments */
            segments: number;
            /** Calls */
            calls: number;
            /** Cache Hits */
            cache_hits: number;
            /** Escalated Segments */
            escalated_segments: number;
            /** Suggestion Ids */
            suggestion_ids: number[];
            /** Predictions */
            predictions: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
            /** Errors */
            errors: string[];
        };
        /** CodeInput */
        CodeInput: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Definition
             * @default
             */
            definition: string;
            /**
             * Include
             * @default
             */
            include: string;
            /**
             * Exclude
             * @default
             */
            exclude: string;
            /** Examples Pos */
            examples_pos?: string[];
            /** Examples Neg */
            examples_neg?: string[];
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "archived";
        };
        /** CodingInput */
        CodingInput: {
            /** Segment Id */
            segment_id: number;
            /** Code Id */
            code_id: number;
            /**
             * Span Start
             * @default 0
             */
            span_start: number;
            /** Span End */
            span_end?: number | null;
            /** Codebook Version Id */
            codebook_version_id?: number | null;
            /**
             * Action
             * @default assign
             * @enum {string}
             */
            action: "assign" | "remove";
            /**
             * Actor
             * @default researcher
             */
            actor: string;
        };
        /** EvaluateInput */
        EvaluateInput: {
            /** Backend */
            backend?: string | null;
            /** Model */
            model?: string | null;
        };
        /** EvaluationResult */
        EvaluationResult: {
            /** Id */
            id: number;
            /** Split */
            split: string;
            /** Backend */
            backend: string;
            /** Model */
            model: string;
            /** Codebook Version Id */
            codebook_version_id: number;
            /** Pipeline Version */
            pipeline_version: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Agent */
            agent: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "KEEP" | "REVERT";
            /** Reason */
            reason: string;
            /** Hypothesis */
            hypothesis: string;
            /** Before Json */
            before_json: string;
            /** After Json */
            after_json: string;
            /** Changed Files Json */
            changed_files_json: string;
            /** Commit Hash */
            commit_hash: string | null;
            /** Tag */
            tag: string | null;
            /** Created At */
            created_at: string;
        };
        /** ExportResult */
        ExportResult: {
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Content */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** IdResult */
        IdResult: {
            /** Id */
            id: number;
        };
        /** ImportInput */
        ImportInput: {
            /** Name */
            name: string;
            /** Content */
            content: string;
            /**
             * Format
             * @enum {string}
             */
            format: "txt" | "md" | "csv";
            /**
             * Text Column
             * @default text
             */
            text_column: string;
            /**
             * Case Column
             * @default case
             */
            case_column: string;
            /**
             * Speaker Column
             * @default speaker
             */
            speaker_column: string;
            /** Attribute Columns */
            attribute_columns?: string[];
            /** Version Of */
            version_of?: number | null;
        };
        /** ImportResult */
        ImportResult: {
            /** New Sources */
            new_sources: number;
            /** Source Ids */
            source_ids: number[];
            /** New Segments */
            new_segments: number;
        };
        /** MemoInput */
        MemoInput: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Segment Id */
            segment_id?: number | null;
            /** Code Id */
            code_id?: number | null;
        };
        /** ProjectInput */
        ProjectInput: {
            /** Name */
            name: string;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** ReviewInput */
        ReviewInput: {
            /** Suggestion Id */
            suggestion_id: number;
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject";
            /**
             * Actor
             * @default researcher
             */
            actor: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workspace */
        Workspace: {
            project: components["schemas"]["ProjectSummary"];
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Segments */
            segments: {
                [key: string]: unknown;
            }[];
            /** Cases */
            cases: {
                [key: string]: unknown;
            }[];
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            }[];
            /** Source Cases */
            source_cases: {
                [key: string]: unknown;
            }[];
            /** Codes */
            codes: {
                [key: string]: unknown;
            }[];
            /** Codebook Versions */
            codebook_versions: {
                [key: string]: unknown;
            }[];
            /** Coding Events */
            coding_events: {
                [key: string]: unknown;
            }[];
            /** Current Codings */
            current_codings: {
                [key: string]: unknown;
            }[];
            /** Suggestions */
            suggestions: {
                [key: string]: unknown;
            }[];
            /** Memos */
            memos: {
                [key: string]: unknown;
            }[];
            /** Experiments */
            experiments: {
                [key: string]: unknown;
            }[];
            /** Evaluation Runs */
            evaluation_runs: {
                [key: string]: unknown;
            }[];
            /** Routing */
            routing: {
                [key: string]: unknown;
            };
            /** Pipeline Version */
            pipeline_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_projects__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_source_api_projects__slug__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_code_api_projects__slug__codes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_code_api_projects__slug__codes__code_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                code_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_api_projects__slug__codebook_freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coding_api_projects__slug__coding_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memo_api_projects__slug__memos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memo_api_projects__slug__memos__memo_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                memo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_projects__slug__cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_projects__slug__cases__case_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieval_api_projects__slug__retrieval_get: {
        parameters: {
            query?: {
                code_id?: number | null;
                case_id?: number | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_api_projects__slug__matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_projects__slug__export_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                no_text?: boolean;
                bundle?: "reproducibility" | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    availability_api_projects__slug__ai_availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_api_projects__slug__classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_projects__slug__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_projects__slug__experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_projects__slug__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_api_projects__slug__analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisOptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_projects__slug__analysis_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
