import type { CSSProperties } from 'react'
import type { WorkspaceController } from '../lib/workspace'
import type { AnalysisController } from '../lib/analysis'
import { Button } from './ui/button'

export function Analysis({ w, analysis: a }: { w: WorkspaceController; analysis: AnalysisController }) {
  const r = a.report
  return <section className="content-page analysis-page" aria-label="Research analysis"><header className="section-heading"><div><p className="caption">Explore coded evidence</p><h2>Research analysis</h2></div><Button disabled={a.loading} onClick={a.reload}>Refresh analysis</Button></header>
    <p>Descriptive analysis of current manual and accepted coding. Pending suggestions and rejected assignments are excluded.</p>
    {w.readOnly && <p className="notice">This public snapshot contains a fixed report from the licensed demo subset. Filters are disabled; charts, evidence, and precomputed exports remain available.</p>}
    <details className="version" open={!w.readOnly}><summary>Analysis criteria</summary><form key={w.slug} onSubmit={a.submit}><fieldset disabled={w.readOnly || a.loading}><legend>Intersect filters</legend><div className="filters">
      <label>Analysis source<select name="source_id" defaultValue={a.appliedOptions.source_id ?? ''}><option value="">All sources</option>{w.data?.sources.map(source => <option key={source.id} value={source.id}>{source.name}</option>)}</select></label>
      <label>Analysis case<select name="case_id" defaultValue={a.appliedOptions.case_id ?? ''}><option value="">All cases</option>{w.data?.cases.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>Literal text query<input name="query" defaultValue={a.appliedOptions.query} maxLength={200} placeholder="Case-insensitive substring" /></label>
      <label>Match selected codes<select name="code_match" defaultValue={a.appliedOptions.code_match}><option value="any">Any selected code</option><option value="all">All selected codes</option></select></label>
      <label>Group by case attribute<select name="group_by" defaultValue={a.appliedOptions.group_by ?? ''}><option value="">No grouping</option>{a.fields.map(field => <option key={field}>{field}</option>)}</select></label>
      <label>Co-occurrence unit<select name="cooccurrence" defaultValue={a.appliedOptions.cooccurrence}><option value="segment">Present in the same segment</option><option value="overlap">Positive-length span overlap</option></select></label>
    </div><details><summary>Code filter ({w.data?.codes.length ?? 0} available)</summary><div className="analysis-choices">{w.data?.codes.map(code => <label className="checkbox" key={code.id}><input type="checkbox" name="code_ids" value={code.id} defaultChecked={a.appliedOptions.code_ids?.includes(code.id)} />{code.name}</label>)}</div><p className="caption">No selection means all codes. Select at most 50; filters do not change the codebook.</p></details>
    <fieldset><legend>Explicit numeric case attributes</legend><p className="caption">Select up to eight fields. Identifiers are never automatically treated as measurements. Missing, conflicting, and invalid values stay visible.</p><div className="analysis-choices">{a.fields.map(field => <label className="checkbox" key={field}><input type="checkbox" name="numeric_fields" value={field} defaultChecked={a.appliedOptions.numeric_fields?.includes(field)} />{field}</label>)}</div>{!a.fields.length && <p className="caption">Add case attributes to enable group comparisons and numeric analysis.</p>}</fieldset>
    <details><summary>Word-frequency options</summary><div className="filters"><label>Minimum word length<input type="number" name="min_word_length" defaultValue={a.appliedOptions.min_word_length} min={1} max={30} /></label><label>Top words<input type="number" name="top_words" defaultValue={a.appliedOptions.top_words} min={1} max={100} /></label><label>Explicit stopwords<textarea name="stopwords" defaultValue={a.appliedOptions.stopwords?.join(', ')} placeholder="Separate with spaces or commas" /></label></div><p className="caption">Unicode casefolded letter/apostrophe tokens. No hidden stopwords or stemming.</p></details><Button type="submit" disabled={w.readOnly || a.loading}>Apply analysis criteria</Button></fieldset></form></details>
    <div aria-live="polite">{a.loading && <p role="status">Calculating descriptive analysis…</p>}{a.error && <p role="alert" className="error">{a.error}</p>}{a.notice && <p className="notice">{a.notice}</p>}</div>
    {!r && !a.loading && !a.error && <p className="empty">No report available.</p>}
    {r && <><p className="caption">Applied criteria: {a.criteria}</p><p><strong>{r.segment_count}</strong> selected segments · <strong>{r.coded_segment_count}</strong> coded segments · <strong>{r.source_count}</strong> sources · <strong>{r.case_count}</strong> linked cases</p>
      {r.warnings.map((warning, index) => <p className="notice" key={index}>{warning}</p>)}
      {!r.segment_count && <p className="empty">No segments match these criteria. Change filters to explore other evidence.</p>}
      <div className="actions"><Button onClick={() => void a.exportReport('json')}>Download analysis JSON</Button><Button onClick={() => void a.exportReport('csv')}>Download case CSV</Button><Button onClick={() => void a.exportReport('python')}>Download Python starter</Button><Button onClick={() => void a.exportReport('r')}>Download R starter</Button></div>
      <p className="caption">Exports omit source text by default. Case names and attributes may still contain sensitive research data. Python and R starters are files for you to review and run separately; Qualia does not execute them. CSV uses stable column IDs; the column dictionary is included in the companion JSON and Python/R starters.</p>
      <h3>Code frequencies</h3><p className="caption">Display names are current code names; source evidence retains frozen historical names. Each segment and case counts at most once per code. Segment denominator: {r.segment_count}; case denominator: {r.case_count}. Select a bar or count to inspect evidence.</p>
      <div className="analysis-chart-scroll"><svg id="analysis-frequency-chart" className="analysis-chart" viewBox={`0 0 760 ${a.barHeight}`} role="group" aria-labelledby="analysis-frequency-title analysis-frequency-description"><title id="analysis-frequency-title">Code frequency — distinct selected segments</title><desc id="analysis-frequency-description">{a.criteria}. Denominator {r.segment_count} segments. Exact counts in the adjacent table.</desc><text x="20" y="24">Distinct selected segments · denominator {r.segment_count}</text>{a.bars.map(row => <g key={row.code_id} role="button" tabIndex={0} aria-label={`${row.name}: ${row.segment_count} segments. Show evidence.`} onClick={() => a.select(row.name, row.segment_ids)} onKeyDown={event => a.activateChart(event, () => a.select(row.name, row.segment_ids))}><title>{row.name}: {row.segment_count} segments</title><rect className="chart-hit" x="0" y={row.y - 14} width="755" height="44" /><text x="20" y={row.y + 10}>{row.name}</text><rect className="chart-bar" x="340" y={row.y - 10} width={row.width} height="30" /><text x={700} y={row.y + 10}>{row.segment_count}</text></g>)}</svg></div><Button onClick={() => a.exportChart('analysis-frequency-chart', 'code-frequencies')}>Download frequency SVG</Button>
      <div className="table-scroll" role="region" tabIndex={0} aria-label="Code frequencies (scrollable)"><table aria-label="Code frequencies"><thead><tr><th>Code</th><th>Distinct segments</th><th>Segment %</th><th>Distinct cases</th><th>Case %</th><th>Frozen codebook versions</th></tr></thead><tbody>{r.frequencies.map(row => <tr key={row.code_id}><th scope="row">{row.name} (#{row.code_id})</th><td><Button onClick={() => a.select(row.name, row.segment_ids)}>{row.segment_count}</Button></td><td className="metric-value">{a.number(row.segment_percent)}</td><td className="metric-value">{row.case_count}</td><td className="metric-value">{a.number(row.case_percent)}</td><td className="metric-value">{row.codebook_version_ids.join(', ') || 'None'}</td></tr>)}</tbody></table></div>
      <h3>Case-group comparisons</h3><p className="caption">Groups use case attributes only. Missing and conflicting values are separate groups. A source linked to several cases can contribute to several groups; percentages must not be added across groups.</p>
      {!r.groups.length && <p className="empty-note">Select a case attribute to compare groups.</p>}{r.groups.map((group, index) => <details className="version" key={index}><summary>{group.value || '(empty)'} · {group.status} · {group.segment_ids.length} segments / {group.case_ids.length} cases</summary><Button onClick={() => a.select(`Group ${group.value} (${group.status})`, group.segment_ids)}>Inspect group evidence</Button><div className="table-scroll" role="region" tabIndex={0} aria-label={`Group ${group.value} frequencies (scrollable)`}><table aria-label={`Group ${group.value} frequencies`}><thead><tr><th>Code</th><th>Segments</th><th>Segment %</th><th>Cases</th><th>Case %</th></tr></thead><tbody>{group.frequencies.map(row => <tr key={row.code_id}><th scope="row">{row.name}</th><td><Button onClick={() => a.select(`${group.value} / ${row.name}`, row.segment_ids)}>{row.segment_count}</Button></td><td className="metric-value">{a.number(row.segment_percent)}</td><td className="metric-value">{row.case_count}</td><td className="metric-value">{a.number(row.case_percent)}</td></tr>)}</tbody></table></div></details>)}
      <h3>Code co-occurrence</h3><p className="caption">Counts: {r.options.cooccurrence === 'overlap' ? 'segments with positive-length span overlap; touching boundaries are excluded' : 'segments containing both codes'}. Jaccard always uses segment-presence intersection / union, independent of overlap mode. Diagonal cells are omitted.</p>
      <div className="table-scroll" role="region" tabIndex={0} aria-label="Code co-occurrence heat table (scrollable)"><table aria-label="Code co-occurrence heat table"><thead><tr><th>Code</th>{r.frequencies.map(code => <th key={code.code_id} scope="col">{code.name}</th>)}</tr></thead><tbody>{a.heatRows.map(row => <tr key={row.code_id}><th scope="row">{row.name}</th>{row.cells.map(cell => <td key={cell.right.code_id}>{cell.pair ? <Button className="matrix-cell" style={{ '--heat': cell.opacity } as CSSProperties} aria-label={`${row.name} and ${cell.right.name}: ${cell.pair.count} segments`} onClick={() => a.select(`${row.name} × ${cell.right.name}`, cell.pair!.segment_ids)}>{cell.pair.count}</Button> : <span className="metric-value">—</span>}</td>)}</tr>)}</tbody></table></div>
      <details className="version"><summary>Exact pair counts and segment-presence Jaccard</summary><div className="table-scroll" role="region" tabIndex={0} aria-label="Co-occurrence pair statistics (scrollable)"><table aria-label="Co-occurrence pair statistics"><thead><tr><th>Codes</th><th>Mode count</th><th>Segment-presence union</th><th>Segment-presence Jaccard</th></tr></thead><tbody>{r.pairs.map(pair => <tr key={`${pair.left_code_id}-${pair.right_code_id}`}><th scope="row">{w.codeName(pair.left_code_id)} × {w.codeName(pair.right_code_id)}</th><td><Button onClick={() => a.select('Code pair evidence', pair.segment_ids)}>{pair.count}</Button></td><td className="metric-value">{pair.union_count}</td><td className="metric-value">{a.number(pair.jaccard)}</td></tr>)}</tbody></table></div></details>
      <h3>Words in selected text</h3><p className="caption">Occurrence counts and distinct-segment counts are different units. Word lists and evidence are visible here; default exports omit words and raw source text.</p><div className="table-scroll" role="region" tabIndex={0} aria-label="Word frequencies (scrollable)"><table aria-label="Word frequencies"><thead><tr><th>Word</th><th>Occurrences</th><th>Distinct segments</th></tr></thead><tbody>{r.words.map(word => <tr key={word.word}><th scope="row">{word.word}</th><td className="metric-value">{word.count}</td><td><Button onClick={() => a.select(`Word: ${word.word}`, word.segment_ids)}>{word.segment_count}</Button></td></tr>)}</tbody></table></div>
      <h3>Numeric case attributes</h3><p className="caption">One observation per selected case. Statistics use finite numeric values only; sample standard deviation needs at least two values. n/a means undefined or unavailable.</p>
      {!r.numeric.length && <p className="empty-note">Select numeric case attributes explicitly to calculate summaries and correlations.</p>}<div className="table-scroll" role="region" tabIndex={0} aria-label="Numeric descriptive statistics (scrollable)"><table aria-label="Numeric descriptive statistics"><thead><tr><th>Field</th><th>Valid</th><th>Missing</th><th>Invalid / conflicting</th><th>Mean</th><th>Median</th><th>Sample SD</th><th>Minimum</th><th>Maximum</th></tr></thead><tbody>{r.numeric.map(row => <tr key={row.field}><th scope="row">{row.field}</th><td className="metric-value">{row.valid}</td><td className="metric-value">{row.missing}</td><td className="metric-value">{row.invalid}</td><td className="metric-value">{a.number(row.mean)}</td><td className="metric-value">{a.number(row.median)}</td><td className="metric-value">{a.number(row.sample_sd)}</td><td className="metric-value">{a.number(row.minimum)}</td><td className="metric-value">{a.number(row.maximum)}</td></tr>)}</tbody></table></div>
      <h3>Numeric relationships</h3><p className="caption">Pearson r describes paired numeric cases, not causation. Fewer than three pairs or a constant field makes r undefined.</p><label>Scatter fields<select value={a.correlationIndex} onChange={event => a.setCorrelationIndex(Number(event.target.value))} disabled={!r.correlations.length}>{!r.correlations.length && <option value={0}>Select at least two numeric fields</option>}{r.correlations.map((row, index) => <option key={index} value={index}>{row.x_field} × {row.y_field}</option>)}</select></label>
      {a.correlation && <><p>Paired cases: {a.correlation.n} · Pearson r: {a.number(a.correlation.pearson_r)}</p><div className="analysis-chart-scroll"><svg id="analysis-scatter-chart" className="analysis-chart" viewBox="0 0 660 400" role="img" aria-labelledby="analysis-scatter-title analysis-scatter-description"><title id="analysis-scatter-title">{a.correlation.x_field} versus {a.correlation.y_field}</title><desc id="analysis-scatter-description">{a.criteria}. {a.correlation.n} paired cases. Pearson r {a.number(a.correlation.pearson_r)}. Exact values below.</desc><path className="chart-axis" d="M70 50V320H590" /><text x="250" y="390">{a.correlation.x_field}</text><text x="20" y="24">{a.correlation.y_field}</text><text x="70" y="348">{a.number(a.scatter.xMin)}</text><text x="540" y="348">{a.number(a.scatter.xMax)}</text><text x="5" y="320">{a.number(a.scatter.yMin)}</text><text x="5" y="65">{a.number(a.scatter.yMax)}</text>{a.scatter.points.map(point => <g key={point.case_id} role="button" tabIndex={0} aria-label={`Case ${point.case_id}: ${point.x}, ${point.y}. Inspect evidence.`} onClick={() => a.selectCase(point.case_id)} onKeyDown={event => a.activateChart(event, () => a.selectCase(point.case_id))}><title>Case {point.case_id}: {point.x}, {point.y}</title><circle className="chart-hit" cx={point.cx} cy={point.cy} r="20" /><circle className="chart-point" cx={point.cx} cy={point.cy} r="5" /></g>)}</svg></div><Button onClick={() => a.exportChart('analysis-scatter-chart', 'numeric-relationship')}>Download scatter SVG</Button><details className="version"><summary>Exact paired case values</summary><div className="table-scroll" role="region" tabIndex={0} aria-label="Scatter case values (scrollable)"><table aria-label="Scatter case values"><thead><tr><th>Case</th><th>{a.correlation.x_field}</th><th>{a.correlation.y_field}</th></tr></thead><tbody>{a.correlation.points.map(point => <tr key={point.case_id}><th scope="row"><Button onClick={() => a.selectCase(point.case_id)}>Case {point.case_id}</Button></th><td className="metric-value">{point.x}</td><td className="metric-value">{point.y}</td></tr>)}</tbody></table></div></details></>}
      <details className="version"><summary>All pairwise correlations</summary><div className="table-scroll" role="region" tabIndex={0} aria-label="Pairwise correlations (scrollable)"><table aria-label="Pairwise correlations"><thead><tr><th>Fields</th><th>Paired n</th><th>Pearson r</th></tr></thead><tbody>{r.correlations.map(row => <tr key={`${row.x_field}-${row.y_field}`}><th scope="row">{row.x_field} × {row.y_field}</th><td className="metric-value">{row.n}</td><td className="metric-value">{a.number(row.pearson_r)}</td></tr>)}</tbody></table></div></details>
      <section id="analysis-evidence" aria-label="Analysis source evidence"><h3>Source evidence</h3><p>{a.drill?.label ?? 'All selected segments'} · {a.evidenceCount} matching segments</p><p className="caption">Showing up to 25 per page from the complete selected segment IDs. The API embeds {r.excerpts.length} excerpts out of {r.excerpt_total}; this view also retrieves matching text from the loaded workspace.</p><div className="actions"><Button onClick={() => a.select('All selected segments', r.selected_segment_ids)}>Show all selected evidence</Button><Button disabled={a.page === 0} onClick={() => a.setPage(a.page - 1)}>Previous evidence page</Button><span className="caption">Page {a.page + 1}</span><Button disabled={(a.page + 1) * 25 >= a.evidenceCount} onClick={() => a.setPage(a.page + 1)}>Next evidence page</Button></div>
        {!a.evidenceCount && <p className="empty-note">No source segments for this selection.</p>}{a.evidence.map(excerpt => <article className="retrieval-card" key={excerpt.segment_id}><div className="section-heading"><p>{excerpt.source_name} · segment {excerpt.segment_id}{excerpt.speaker ? ` · ${excerpt.speaker}` : ''}</p><Button onClick={() => w.openSegment(excerpt.segment_id)}>Open transcript</Button></div><blockquote>{excerpt.text}</blockquote><details><summary>Coding evidence ({excerpt.events.length} current events)</summary>{excerpt.events.map(event => <dl className="provenance" key={event.id}><dt>Event / frozen code name</dt><dd>#{event.id} · {w.eventCodeName(event)}</dd><dt>Decision / actor</dt><dd>{event.action} · {event.actor} · {event.created_at}</dd><dt>Span (Unicode code points)</dt><dd>{event.span_start}–{event.span_end}</dd><dt>Frozen codebook / pipeline</dt><dd>{event.codebook_version_id} · {event.pipeline_version}</dd><dt>Backend / model / prompt</dt><dd>{event.backend ?? 'manual'} · {event.model ?? 'n/a'} · {event.prompt_hash || 'n/a'}</dd><dt>Rationale</dt><dd>{event.rationale || 'Not recorded'}</dd></dl>)}</details></article>)}
      </section><details className="version"><summary>Analysis methods and provenance</summary><dl><dt>Input hash</dt><dd>{r.input_hash}</dd><dt>Pipeline</dt><dd>{r.pipeline_version}</dd><dt>Frozen codebooks</dt><dd>{r.codebook_version_ids.join(', ') || 'None'}</dd><dt>Codebook hashes</dt><dd>{JSON.stringify(r.codebook_hashes)}</dd><dt>Current coding event IDs</dt><dd>{r.coding_event_ids.join(', ') || 'None'}</dd></dl><ul>{r.methods.map((method, index) => <li key={index}>{method}</li>)}</ul></details>
    </>}
  </section>
}
