import { useWorkspace } from '../lib/workspace'
import { Transcript, CodingPanel } from './Transcript'
import { Codebook } from './Codebook'
import { Memos } from './Memos'
import { Retrieval, Matrix } from './Retrieval'
import { WorkspaceForms } from './WorkspaceForms'
import { Button } from './ui/button'

export function App() {
  const w = useWorkspace()
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to research workspace</a>
    <header className="app-header"><div className="brand"><h1>Qualia</h1><p className="caption">Qualitative coding you can audit.</p></div><div className="project-controls"><label>Local project<select value={w.slug} disabled={w.busy} onChange={event => w.chooseProject(event.target.value)}><option value="" disabled>Choose a project</option>{w.projects.map(project => <option key={project.slug} value={project.slug}>{project.name}</option>)}</select></label><details className="project-create"><summary>New project</summary><form onSubmit={w.createProject}><label>Project identifier<input name="name" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="field-study" maxLength={80} /></label><p className="caption">Lowercase words separated by hyphens.</p><Button type="submit" disabled={w.busy}>Create local project</Button></form></details></div><span className="local-status caption">Local workspace · external AI off by default</span></header>
    <div className="messages" aria-live="polite">{w.error && <p role="alert" className="error">Error: {w.error}</p>}{w.notice && <p className="notice">{w.notice}</p>}{w.busy && <p role="status" className="caption">Saving…</p>}</div>
    {w.loading ? <main id="main-content" className="landing"><p role="status">Opening your local research workspace…</p></main> : !w.slug ? <main id="main-content" className="landing"><p className="caption">Your evidence. Your methods.</p><h2>Begin with a question.</h2><p>Create a local project above, then import transcripts and build your codebook. No account or model connection is needed for manual research.</p></main> : !w.data ? <main id="main-content" className="landing"><h2>Project unavailable</h2><Button onClick={() => void w.run(async () => { await w.reload() })}>Retry opening project</Button></main> : <>
      <nav className="workspace-nav" aria-label="Research views"><Button aria-current={w.view === 'workspace' ? 'page' : undefined} onClick={() => w.setView('workspace')}>Workspace</Button><Button aria-current={w.view === 'codebook' ? 'page' : undefined} onClick={() => w.setView('codebook')}>Codebook</Button><Button aria-current={w.view === 'memos' ? 'page' : undefined} onClick={() => w.setView('memos')}>Memos</Button><Button aria-current={w.view === 'retrieval' ? 'page' : undefined} onClick={() => w.setView('retrieval')}>Retrieval</Button><Button aria-current={w.view === 'matrix' ? 'page' : undefined} onClick={() => w.setView('matrix')}>Matrix</Button><Button className="export-action" onClick={() => w.setPanel('export')}>Export</Button></nav>
      <WorkspaceForms w={w} />
      <main id="main-content" tabIndex={-1}>
        {w.view === 'workspace' && <div className="workspace-grid"><aside className="source-panel" aria-label="Sources and cases"><div className="section-heading"><h2>Sources</h2><span className="caption">{w.sources.length}</span></div><Button onClick={() => w.setPanel('import')}>Import source</Button><label>Filter by case<select value={w.caseId ?? ''} onChange={event => w.setCaseId(Number(event.target.value) || null)}><option value="">All cases</option>{w.data.cases.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><ul className="source-list">{w.sources.map(source => <li key={source.id}><Button className={w.source?.id === source.id ? 'selected-source' : ''} onClick={() => w.selectSource(source.id)}>{source.name}</Button></li>)}</ul><h3>Cases</h3><Button onClick={() => { w.setEditCase(null); w.setPanel('case') }}>Create case</Button>{w.data.cases.map(item => <div className="case-row" key={item.id}><span>{item.name}</span><Button aria-label={`Edit case ${item.name}`} onClick={() => { w.setEditCase(item); w.setPanel('case') }}>Edit</Button></div>)}<h3>Code tree</h3><ul className="code-tree">{w.codes.map(code => <li key={code.id}><span className="caption">{code.depth ? '↳ ' : ''}</span>{code.name}<span className="caption">{code.status === 'archived' ? ' · archived' : ''}</span></li>)}</ul><Button onClick={() => w.setView('codebook')}>Manage codebook</Button><h3>Memos</h3>{w.data.memos.map(memo => <Button key={memo.id} className="memo-link" onClick={() => { w.setEditMemo(memo); w.setView('memos') }}>{memo.title}</Button>)}</aside><Transcript w={w} /><CodingPanel w={w} /></div>}
        {w.view === 'codebook' && <Codebook w={w} />}{w.view === 'memos' && <Memos w={w} />}{w.view === 'retrieval' && <Retrieval w={w} />}{w.view === 'matrix' && <Matrix w={w} />}
      </main>
    </>}
    <footer className="app-footer caption">Qualia · Researcher controls the methodology. Every code keeps its evidence.</footer>
  </div>
}
