import type { WorkspaceController } from '../lib/workspace'
import { Button } from './ui/button'

export function Memos({ w }: { w: WorkspaceController }) {
  return <section className="content-page memos-page" aria-label="Memos"><header className="section-heading"><div><p className="caption">Field notes</p><h2>Memos</h2></div><Button disabled={w.readOnly} onClick={() => w.setEditMemo(null)}>New memo</Button></header><div className="two-column"><div>
    {!w.data?.memos.length && <div className="empty"><h3>Keep your interpretation beside the evidence</h3><p>Write a memo and optionally link it to a segment or code.</p></div>}
    {w.data?.memos.map(memo => <article key={memo.id} className="memo-card"><h3>{memo.title}</h3><p className="preserve-lines">{memo.text}</p><div className="actions">{memo.segment_id !== null && <Button onClick={() => w.openSegment(memo.segment_id!)}>Segment {memo.segment_id}</Button>}{memo.code_id !== null && <span className="caption">Code: {w.codeName(memo.code_id)}</span>}<Button disabled={w.readOnly} onClick={() => w.setEditMemo(memo)}>Edit memo</Button></div></article>)}
  </div><form className="editor" key={w.editMemo?.id ?? 'new'} onSubmit={w.saveMemo}><fieldset disabled={w.readOnly}><h3>{w.editMemo ? 'Edit memo' : 'Write memo'}</h3><label>Title<input name="title" required maxLength={200} defaultValue={w.editMemo?.title ?? ''} /></label><label>Memo<textarea name="text" rows={10} defaultValue={w.editMemo?.text ?? ''} /></label><label>Linked segment<select name="segment_id" defaultValue={w.editMemo?.segment_id ?? ''}><option value="">No linked segment</option>{w.data?.segments.map(segment => <option key={segment.id} value={segment.id}>Segment {segment.id} · source {segment.source_id}</option>)}</select></label><label>Linked code<select name="code_id" defaultValue={w.editMemo?.code_id ?? ''}><option value="">No linked code</option>{w.codes.map(code => <option key={code.id} value={code.id}>{code.name}</option>)}</select></label><Button type="submit" className="primary" disabled={w.readOnly || w.busy}>Save memo</Button></fieldset></form></div></section>
}
